const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/authMiddleware');
const legacyController = require('../controllers/proofOfReservesController');
const integrityService = require('../services/proofOfReservesIntegrityService');
const logger = require('../src/config/logger');

const protect = authMiddleware.protect;
const adminOnly = authMiddleware.adminOnly;

// Public read: never mutate state or create database rows merely because the
// solvency page was opened. A snapshot is generated by the authenticated
// refresh endpoint below on an operational cadence.
router.get('/', async (req, res) => {
  try {
    const snapshot = await integrityService.getLatestSnapshot();
    if (!snapshot) return res.status(404).json({ success: false, message: 'No reserve snapshot available.' });
    return res.json({ success: true, ...snapshot });
  } catch (err) {
    logger.error({ err: err.message }, '[proofOfReserves] latest snapshot failed');
    return res.status(500).json({ success: false, message: 'Failed to load reserve snapshot.' });
  }
});

router.get('/history', legacyController.getReserveHistory);

// Admin-only refresh: snapshot creation is an operational mutation and is
// therefore deliberately separated from the public read endpoint.
router.post('/refresh', protect, adminOnly, async (req, res) => {
  try {
    const { snapshot } = await integrityService.createSnapshot();
    return res.status(201).json({ success: true, snapshotId: snapshot.id, timestamp: snapshot.createdAt.toISOString(), merkleRoot: snapshot.merkleRoot, isFullyBacked: snapshot.isFullyBacked, totalLiabilities: snapshot.totalLiabilities.toString(), totalReserves: snapshot.totalReserves.toString() });
  } catch (err) {
    logger.error({ err: err.message }, '[proofOfReserves] refresh failed');
    return res.status(500).json({ success: false, message: 'Failed to generate reserve snapshot.' });
  }
});

router.get('/verify', protect, async (req, res) => {
  try {
    const result = await integrityService.verifyUser(req.user.id, req.query.snapshotId);
    if (!result) return res.status(404).json({ success: false, message: 'No snapshot available.' });
    if (!result.verified) return res.status(409).json({ success: false, data: result });
    return res.json({ success: true, verified: true, snapshotId: result.snapshot.id, merkleRoot: result.snapshot.merkleRoot, proof: result.proof, snapshotTimestamp: result.snapshot.createdAt.toISOString(), yourBalance: result.yourBalance });
  } catch (err) {
    logger.error({ err: err.message }, '[proofOfReserves] verification failed');
    return res.status(500).json({ success: false, message: 'Verification failed.' });
  }
});

module.exports = router;
