const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/authMiddleware');
const legacyController = require('../controllers/proofOfReservesController');
const integrityService = require('../services/proofOfReservesIntegrityService');
const logger = require('../src/config/logger');

const protect = authMiddleware.protect;

// Current snapshots are generated by the integrity service, which atomically
// persists the exact per-user balance commitments used to construct the root.
router.get('/', async (req, res) => {
  try {
    const { snapshot } = await integrityService.createSnapshot();
    return res.json({
      success: true,
      timestamp: snapshot.createdAt.toISOString(),
      totalLiabilities: snapshot.totalLiabilities.toString(),
      totalReserves: snapshot.totalReserves.toString(),
      reserveRatio: snapshot.reserveRatio.toString(),
      isFullyBacked: snapshot.isFullyBacked,
      userCount: snapshot.userCount,
      merkleRoot: snapshot.merkleRoot,
      breakdown: snapshot.breakdown,
    });
  } catch (err) {
    logger.error({ err: err.message }, '[proofOfReserves] integrity snapshot failed');
    return res.status(500).json({ success: false, message: 'Failed to generate reserve snapshot.' });
  }
});

// Historical snapshots remain public. The immutable leaf commitments are not
// exposed here; users obtain their own historical proof through /verify.
router.get('/history', legacyController.getReserveHistory);

router.get('/verify', protect, async (req, res) => {
  try {
    const result = await integrityService.verifyUser(req.user.id, req.query.snapshotId);
    if (!result) return res.status(404).json({ success: false, message: 'No snapshot available.' });
    if (!result.verified) return res.status(409).json({ success: false, data: result });
    return res.json({
      success: true,
      verified: true,
      snapshotId: result.snapshot.id,
      merkleRoot: result.snapshot.merkleRoot,
      proof: result.proof,
      snapshotTimestamp: result.snapshot.createdAt.toISOString(),
      yourBalance: result.yourBalance,
    });
  } catch (err) {
    logger.error({ err: err.message }, '[proofOfReserves] verification failed');
    return res.status(500).json({ success: false, message: 'Verification failed.' });
  }
});

module.exports = router;
