-- r272 follow-up (P0): authoritative source of truth for specialized admin
-- roles. The Role enum only holds USER/VENDOR/ADMIN, so FINANCE_ADMIN /
-- COMPLIANCE_ADMIN (required participants for >= 50,000 USDC withdrawal
-- approvals) could never be assigned to a real account — the tier invariant
-- was unsatisfiable in production and the role catalog was documentary.
-- This table is the ONLY persistent source of a specialized admin role; the
-- resolver (adminRbacController.resolveEffectiveAdminRole) additionally
-- requires the account to still hold User.role = ADMIN.
CREATE TABLE "AdminRoleAssignment" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "userId" INTEGER NOT NULL,
    "role" VARCHAR(30) NOT NULL,
    "assignedBy" INTEGER,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdminRoleAssignment_pkey" PRIMARY KEY ("id")
);

-- One specialized role per account: the assignment IS the admin's
-- designation; multiple conflicting rows would create two effective roles.
CREATE UNIQUE INDEX "AdminRoleAssignment_userId_key" ON "AdminRoleAssignment"("userId");
