'use strict';

const logger = require('../src/config/logger');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function seedThemes() {
  logger.info('[Seed] Seeding storefront themes...');

  const themes = [
    {
      key: 'classic_light',
      name: 'Classic Light',
      description: 'Clean, bright, universal default theme',
      tier: 'FREE',
      minAzmStake: 0,
      category: 'UNIVERSAL',
      tokenSet: {
        background: '#F7F5F2',
        surface: 'rgba(255,255,255,0.72)',
        surfaceSolid: '#FFFFFF',
        border: 'rgba(17,17,17,0.08)',
        textPrimary: '#15141A',
        textSecondary: '#5D5A66',
        textMuted: '#9A96A3',
        accent: '#6C4FD1',
        accentHover: '#7C61DD',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Inter', body: 'Inter' },
      borderRadius: 'medium',
      spacingScale: 1.0,
      isActive: true,
      displayOrder: 0,
    },
    {
      key: 'midnight_pro',
      name: 'Midnight Pro',
      description: 'Dark, sleek, premium feel',
      tier: 'NITRO_BRONZE',
      minAzmStake: 500,
      category: 'UNIVERSAL',
      tokenSet: {
        background: '#0F0E13',
        surface: 'rgba(30,28,38,0.65)',
        surfaceSolid: '#1E1C26',
        border: 'rgba(255,255,255,0.08)',
        textPrimary: '#F0F0F5',
        textSecondary: '#C6BDCF',
        textMuted: '#776589',
        accent: '#6C4FD1',
        accentHover: '#7C61DD',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Inter', body: 'Inter' },
      borderRadius: 'medium',
      spacingScale: 1.0,
      isActive: true,
      displayOrder: 1,
    },
    {
      key: 'warm_sunset',
      name: 'Warm Sunset',
      description: 'Inviting amber-orange palette for food & hospitality',
      tier: 'NITRO_BRONZE',
      minAzmStake: 500,
      category: 'RESTAURANT',
      tokenSet: {
        background: '#FFF8F0',
        surface: 'rgba(255,255,255,0.72)',
        surfaceSolid: '#FFFFFF',
        border: 'rgba(180,100,20,0.12)',
        textPrimary: '#2A1A0A',
        textSecondary: '#7A5A3A',
        textMuted: '#A89070',
        accent: '#E07B30',
        accentHover: '#F08B40',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Poppins', body: 'Inter' },
      borderRadius: 'large',
      spacingScale: 1.1,
      isActive: true,
      displayOrder: 2,
    },
    {
      key: 'ocean_breeze',
      name: 'Ocean Breeze',
      description: 'Cool blue-teal palette for hotels & travel',
      tier: 'NITRO_SILVER',
      minAzmStake: 2000,
      category: 'HOTEL',
      tokenSet: {
        background: '#F0F7FA',
        surface: 'rgba(255,255,255,0.72)',
        surfaceSolid: '#FFFFFF',
        border: 'rgba(20,80,120,0.10)',
        textPrimary: '#0A2030',
        textSecondary: '#3A6070',
        textMuted: '#7090A0',
        accent: '#0E8A9A',
        accentHover: '#1E9AAB',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Poppins', body: 'Inter' },
      borderRadius: 'medium',
      spacingScale: 1.0,
      isActive: true,
      displayOrder: 3,
    },
    {
      key: 'forest_glow',
      name: 'Forest Glow',
      description: 'Natural green palette for grocery & organic',
      tier: 'NITRO_SILVER',
      minAzmStake: 2000,
      category: 'GROCERY',
      tokenSet: {
        background: '#F5FAF5',
        surface: 'rgba(255,255,255,0.72)',
        surfaceSolid: '#FFFFFF',
        border: 'rgba(20,100,40,0.10)',
        textPrimary: '#0A2A10',
        textSecondary: '#3A6A40',
        textMuted: '#70A070',
        accent: '#2BA050',
        accentHover: '#3BB060',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Inter', body: 'Inter' },
      borderRadius: 'small',
      spacingScale: 0.95,
      isActive: true,
      displayOrder: 4,
    },
    {
      key: 'royal_gold',
      name: 'Royal Gold',
      description: 'Luxurious gold-on-black for premium brands',
      tier: 'NITRO_GOLD',
      minAzmStake: 5000,
      category: 'UNIVERSAL',
      tokenSet: {
        background: '#0A0A0A',
        surface: 'rgba(40,38,30,0.65)',
        surfaceSolid: '#1E1C14',
        border: 'rgba(212,175,55,0.12)',
        textPrimary: '#F5EFC0',
        textSecondary: '#C6B070',
        textMuted: '#807040',
        accent: '#D4AF37',
        accentHover: '#E4BF47',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Playfair Display', body: 'Inter' },
      borderRadius: 'medium',
      spacingScale: 1.0,
      isActive: true,
      displayOrder: 5,
    },
    {
      key: 'neon_pulse',
      name: 'Neon Pulse',
      description: 'Vibrant gradient palette for fashion & retail',
      tier: 'NITRO_GOLD',
      minAzmStake: 5000,
      category: 'RETAIL',
      tokenSet: {
        background: '#0F0A1A',
        surface: 'rgba(30,20,50,0.65)',
        surfaceSolid: '#1A1430',
        border: 'rgba(180,80,255,0.12)',
        textPrimary: '#F0E8FF',
        textSecondary: '#B0A0D0',
        textMuted: '#705890',
        accent: '#B050FF',
        accentHover: '#C060FF',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Poppins', body: 'Inter' },
      borderRadius: 'large',
      spacingScale: 1.05,
      isActive: true,
      displayOrder: 6,
    },
    {
      key: 'minimal_mono',
      name: 'Minimal Mono',
      description: 'Monochrome minimalist for professional services',
      tier: 'FREE',
      minAzmStake: 0,
      category: 'UNIVERSAL',
      tokenSet: {
        background: '#FAFAFA',
        surface: 'rgba(255,255,255,0.80)',
        surfaceSolid: '#FFFFFF',
        border: 'rgba(0,0,0,0.06)',
        textPrimary: '#111111',
        textSecondary: '#555555',
        textMuted: '#999999',
        accent: '#333333',
        accentHover: '#444444',
        success: '#1FA37A',
        warning: '#E2A33D',
        danger: '#E15361',
        info: '#3D74DB',
      },
      typography: { heading: 'Inter', body: 'Inter' },
      borderRadius: 'small',
      spacingScale: 0.9,
      isActive: true,
      displayOrder: 7,
    },
  ];

  for (const theme of themes) {
    await prisma.businessStorefrontTheme.upsert({
      where: { key: theme.key },
      create: theme,
      update: theme,
    });
  }

  logger.info(`[Seed] ${themes.length} storefront themes seeded`);
}

module.exports = { seedThemes };

if (require.main === module) {
  seedThemes()
    .catch((e) => { logger.error(e); process.exit(1); })
    .finally(() => prisma.$disconnect());
}
